version: '3.7'

services:
  app:
    # build . will create the image such as a previous command typed.
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/user/app # will send everything to the workdir created previously
